from singleCell import *
from ruleMaker import *
# import pkg_resources
import pandas as pd
import networkx as nx
import pickle

def scBonita_testData():
    """Returns the data needed to run the scBonita tutorials.
    Returns a dictionary of objects:
        1. originalGraph: networkx DiGraph of the original KEGG network "hsa00010" as processed by scBONITA's KEGG parser
        2. trainingData: pandas DataFrame of a test single-cell RNAseq dataset. Rows = genes, Columns = cell IDs, Values = log2(transcripts per 10000) normalized reads
        3. processedGraph: networkx DiGraph of the KEGG network "hsa00010" as processed by scBONITA for the test data set
        4. importanceScores: pandas DataFrame of a table of nodes in processedGraph and the importance scores calculated by scBONITA for processedGraph using testData
        5. scObject: singleCell object generated by the rule inference pipeline
        6. metaData: meta data for each cell in the test data set
        7. contrast: conditions to be compared using scBONITA pathway analysis, for the test dataset and test network
        8. embeddings: PCA projection of the test dataset
    """
    # This is a stream-like object. If you want the actual info, call
    # stream.read()
    #stream = pkg_resources.resource_stream(__name__, 'data/emperors.csv')
    #return pd.read_csv(stream, encoding='latin-1')
    #return pd.read_csv('data/emperors.csv', encoding='latin-1')
    testData = {}
    testData["originalGraph"] =  nx.read_graphml("data/hsa00010.graphml")
    testData["processedGraph"] = nx.read_graphml("data/hsa00010.graphml_processed.graphml")
    testData["trainingData"] = pd.read_csv("data/trainingData.csv", index_col = 0)
    testData["importanceScores"] = pd.read_csv("data/hsa00010.graphml_processed.graphml_importanceScores.csv")
    testData["scObject"] = pickle.load(open("data/trainingData.binscTest.pickle", "rb"))
    testData["metaData"] = pd.read_csv("data/conditions.txt", index_col=0)
    testData["contrast"] = pd.read_csv("data/contrasts.txt", sep = "\t", header=None)
    testData["embeddings"] = pd.read_csv("data/testData_embeddings.csv", index_col=0)
    return testData

